import {
  Enterprise,
  Prospect,
  AIAudit,
  Diagnostic,
  VisualAsset,
  DocumentItem,
  Campaign,
  WhatsAppTemplate,
  ConversationalAgent,
  CRMDeal,
  AlertNotification,
  SystemServiceStatus,
  SystemLogEntry,
  User,
} from '../types';

export const MOCK_ENTERPRISES: Enterprise[] = [
  {
    id: 'ent_01',
    nit: '900.412.890-1',
    name: 'Grupo Logístico del Caribe S.A.',
    industry: 'Manufactura',
    employees: '250 - 500',
    location: 'Barranquilla, Colombia',
    score: 88,
    status: 'Auditado',
    website: 'https://grupologisticocaribe.co',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'ent_02',
    nit: '830.056.230-4',
    name: 'Bancaria Digital Andina',
    industry: 'Finanzas',
    employees: '1000+',
    location: 'Bogotá, Colombia',
    score: 94,
    status: 'Cliente',
    website: 'https://bancariaandina.com',
    createdAt: '2025-01-12T14:30:00Z',
  },
  {
    id: 'ent_03',
    nit: '901.233.109-8',
    name: 'AgroSalud BioTech',
    industry: 'Salud',
    employees: '100 - 250',
    location: 'Medellín, Colombia',
    score: 65,
    status: 'En Prospección',
    website: 'https://agrosaludbiotech.org',
    createdAt: '2025-02-01T09:15:00Z',
  },
  {
    id: 'ent_04',
    nit: '800.198.542-9',
    name: 'Soluciones Cloud Latam',
    industry: 'Tecnología',
    employees: '50 - 100',
    location: 'Cali, Colombia',
    score: 91,
    status: 'Auditado',
    website: 'https://solucionescloud.io',
    createdAt: '2025-02-15T11:20:00Z',
  },
  {
    id: 'ent_05',
    nit: '900.871.223-5',
    name: 'Instituto Educativo Superior Innova',
    industry: 'Educación',
    employees: '500 - 1000',
    location: 'Bucaramanga, Colombia',
    score: 42,
    status: 'Sin Analizar',
    website: 'https://innovasuperior.edu.co',
    createdAt: '2025-03-01T08:00:00Z',
  },
];

export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: 'pro_01',
    companyName: 'Bancaria Digital Andina',
    contactName: 'Mateo Restrepo (VP Operaciones)',
    email: 'mrestrepo@bancariaandina.com',
    phone: '+57 310 458 9012',
    stage: 'Cerrado Ganado',
    value: '$48,000,000 COP',
    score: 96,
    lastContact: 'Hace 2 horas',
  },
  {
    id: 'pro_02',
    companyName: 'Grupo Logístico del Caribe S.A.',
    contactName: 'Carolina Gómez (Directora TI)',
    email: 'cgomez@grupologisticocaribe.co',
    phone: '+57 300 892 1144',
    stage: 'En Negociación',
    value: '$32,500,000 COP',
    score: 89,
    lastContact: 'Ayer',
  },
  {
    id: 'pro_03',
    companyName: 'AgroSalud BioTech',
    contactName: 'Dr. Fernando Páez (Gerente)',
    email: 'fpaez@agrosaludbiotech.org',
    phone: '+57 315 220 3399',
    stage: 'Diagnóstico Enviado',
    value: '$18,000,000 COP',
    score: 74,
    lastContact: 'Hace 3 días',
  },
  {
    id: 'pro_04',
    companyName: 'Soluciones Cloud Latam',
    contactName: 'Sonia Silva (CTO)',
    email: 'ssilva@solucionescloud.io',
    phone: '+57 318 901 2233',
    stage: 'Lead Contactado',
    value: '$25,000,000 COP',
    score: 82,
    lastContact: 'Hace 5 días',
  },
];

export const MOCK_AI_AUDITS: AIAudit[] = [
  {
    id: 'aud_01',
    enterpriseName: 'Grupo Logístico del Caribe S.A.',
    industry: 'Manufactura',
    readinessScore: 88,
    digitalMaturity: 'Alta',
    opportunitiesFound: 14,
    status: 'Completado',
    date: '2025-03-20',
  },
  {
    id: 'aud_02',
    enterpriseName: 'AgroSalud BioTech',
    industry: 'Salud',
    readinessScore: 65,
    digitalMaturity: 'Media',
    opportunitiesFound: 9,
    status: 'Completado',
    date: '2025-03-22',
  },
  {
    id: 'aud_03',
    enterpriseName: 'Instituto Educativo Superior Innova',
    industry: 'Educación',
    readinessScore: 42,
    digitalMaturity: 'Baja',
    opportunitiesFound: 21,
    status: 'En Proceso',
    date: '2025-03-25',
  },
];

export const MOCK_DIAGNOSTICS: Diagnostic[] = [
  {
    id: 'diag_101',
    code: 'DX-2025-001',
    enterpriseName: 'Bancaria Digital Andina',
    version: 'v2.1',
    riskLevel: 'Bajo',
    recommendationsCount: 12,
    createdAt: '2025-03-15',
    status: 'Aprobado',
  },
  {
    id: 'diag_102',
    code: 'DX-2025-002',
    enterpriseName: 'Grupo Logístico del Caribe S.A.',
    version: 'v1.0',
    riskLevel: 'Medio',
    recommendationsCount: 18,
    createdAt: '2025-03-21',
    status: 'Enviado',
  },
  {
    id: 'diag_103',
    code: 'DX-2025-003',
    enterpriseName: 'AgroSalud BioTech',
    version: 'v1.0-draft',
    riskLevel: 'Alto',
    recommendationsCount: 25,
    createdAt: '2025-03-24',
    status: 'Borrador',
  },
];

export const MOCK_VISUAL_ASSETS: VisualAsset[] = [
  {
    id: 'img_01',
    title: 'Banner Campaña Financiera B2B',
    category: 'Campaña',
    dimensions: '1200x630 (16:9)',
    status: 'Generado',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    createdAt: '2025-03-18',
  },
  {
    id: 'img_02',
    title: 'Infografía Diagnóstico Manufactura',
    category: 'Diagnóstico',
    dimensions: '1080x1350 (4:5)',
    status: 'Generado',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80',
    createdAt: '2025-03-20',
  },
  {
    id: 'img_03',
    title: 'Mockup Plataforma ASYS AIP',
    category: 'Branding',
    dimensions: '1920x1080 (16:9)',
    status: 'Generado',
    url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80',
    createdAt: '2025-03-22',
  },
];

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_01',
    title: 'Propuesta_Comercial_BancariaAndina_v2.pdf',
    type: 'Propuesta Comercial',
    size: '3.4 MB',
    format: 'PDF',
    createdAt: '2025-03-16',
    author: 'Carlos Mendoza',
  },
  {
    id: 'doc_02',
    title: 'Informe_Diagnostico_GrupoLogistico.pdf',
    type: 'Informe Diagnóstico',
    size: '5.1 MB',
    format: 'PDF',
    createdAt: '2025-03-21',
    author: 'Valeria Ríos',
  },
  {
    id: 'doc_03',
    title: 'Plantilla_Contrato_SaaS_Empresarial.docx',
    type: 'Plantilla',
    size: '890 KB',
    format: 'DOCX',
    createdAt: '2025-01-10',
    author: 'Legal ASYS',
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp_01',
    name: 'Transformación Digital Sector Financiero 2025',
    channel: 'Omnicanal',
    leadsCount: 450,
    openRate: '68.4%',
    conversionRate: '14.2%',
    status: 'Activa',
    startDate: '2025-03-01',
  },
  {
    id: 'cmp_02',
    name: 'Diagnósticos IA para Sector Salud',
    channel: 'LinkedIn',
    leadsCount: 180,
    openRate: '52.1%',
    conversionRate: '8.7%',
    status: 'Pausada',
    startDate: '2025-02-15',
  },
  {
    id: 'cmp_03',
    name: 'Outreach WhatsApp Empresas Manufactura',
    channel: 'WhatsApp',
    leadsCount: 320,
    openRate: '91.0%',
    conversionRate: '22.5%',
    status: 'Activa',
    startDate: '2025-03-10',
  },
];

export const MOCK_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'wa_01',
    name: 'diagnostico_ia_ready_v1',
    category: 'UTILITY',
    language: 'es_CO',
    status: 'APROBADO',
    lastUsed: 'Hace 1 hora',
  },
  {
    id: 'wa_02',
    name: 'invitacion_webinar_empresarial',
    category: 'MARKETING',
    language: 'es_CO',
    status: 'APROBADO',
    lastUsed: 'Ayer',
  },
  {
    id: 'wa_03',
    name: 'confirmacion_cita_consultor',
    category: 'UTILITY',
    language: 'es_CO',
    status: 'PENDIENTE',
    lastUsed: 'Nunca',
  },
];

export const MOCK_AGENTS: ConversationalAgent[] = [
  {
    id: 'ag_01',
    name: 'Auditor IA Principal',
    model: 'Gemini 1.5 Pro',
    activeSessions: 12,
    status: 'En Línea',
    avgResponseTime: '1.2s',
  },
  {
    id: 'ag_02',
    name: 'Asistente Prospección B2B',
    model: 'Claude 3.5 Sonnet',
    activeSessions: 5,
    status: 'En Línea',
    avgResponseTime: '0.9s',
  },
  {
    id: 'ag_03',
    name: 'Agente Cualificador WhatsApp',
    model: 'GPT-4o',
    activeSessions: 0,
    status: 'Standby',
    avgResponseTime: '1.5s',
  },
];

export const MOCK_CRM_DEALS: CRMDeal[] = [
  {
    id: 'deal_01',
    title: 'Implementación AIP Enterprise',
    company: 'Bancaria Digital Andina',
    amount: '$48,000,000 COP',
    probability: '100%',
    stage: 'Cierre',
    owner: 'Carlos Mendoza',
  },
  {
    id: 'deal_02',
    title: 'Módulo Diagnóstico Automático',
    company: 'Grupo Logístico del Caribe',
    amount: '$32,500,000 COP',
    probability: '80%',
    stage: 'Negociación',
    owner: 'Valeria Ríos',
  },
  {
    id: 'deal_03',
    title: 'Auditoría IA & Campañas WhatsApp',
    company: 'AgroSalud BioTech',
    amount: '$18,000,000 COP',
    probability: '50%',
    stage: 'Propuesta',
    owner: 'Carlos Mendoza',
  },
];

export const MOCK_ALERTS: AlertNotification[] = [
  {
    id: 'alt_01',
    title: 'Nuevo Lead Calificado Detectado',
    message: 'Bancaria Digital Andina ha superado el score de 90 puntos en prospección.',
    type: 'success',
    timestamp: '2025-03-25T14:30:00Z',
    read: false,
    source: 'LeadScoringEngine',
  },
  {
    id: 'alt_02',
    title: 'Tasa de Uso de Memoria Redis en 72%',
    message: 'Se recomienda monitorear el cluster de cache ante posibles picos de concurrencia.',
    type: 'warning',
    timestamp: '2025-03-25T12:10:00Z',
    read: true,
    source: 'RedisMonitorService',
  },
  {
    id: 'alt_03',
    title: 'Token Meta Business Pro próximo a vencer',
    message: 'El access token de la API de WhatsApp Business vence en 3 días.',
    type: 'error',
    timestamp: '2025-03-24T09:00:00Z',
    read: false,
    source: 'WhatsAppChannelWorker',
  },
];

export const MOCK_SYSTEM_SERVICES: SystemServiceStatus[] = [
  {
    name: 'FastAPI REST Core Engine',
    category: 'Core',
    status: 'Healthy',
    latency: '14ms',
    uptime: '99.98%',
    lastCheck: 'Hace 5 segundos',
  },
  {
    name: 'PostgreSQL Database Cluster',
    category: 'Database',
    status: 'Healthy',
    latency: '3ms',
    uptime: '99.99%',
    lastCheck: 'Hace 2 segundos',
  },
  {
    name: 'Redis Distributed Cache & Broker',
    category: 'Cache',
    status: 'Healthy',
    latency: '1ms',
    uptime: '100.00%',
    lastCheck: 'Hace 1 segundo',
  },
  {
    name: 'Celery Task Worker Engine',
    category: 'Worker',
    status: 'Healthy',
    latency: '22ms',
    uptime: '99.95%',
    lastCheck: 'Hace 10 segundos',
  },
  {
    name: 'Traefik / Nginx Edge Gateway',
    category: 'Gateway',
    status: 'Healthy',
    latency: '2ms',
    uptime: '100.00%',
    lastCheck: 'Hace 1 segundo',
  },
];

export const MOCK_SYSTEM_LOGS: SystemLogEntry[] = [
  {
    id: 'log_1001',
    timestamp: '2025-03-25T14:32:01.412Z',
    level: 'INFO',
    service: 'access',
    message: 'POST /api/v1/auth/login 200 OK - User: admin@asysdigital.com',
    ip: '190.157.44.12',
  },
  {
    id: 'log_1002',
    timestamp: '2025-03-25T14:30:15.890Z',
    level: 'INFO',
    service: 'application',
    message: 'AuditorIARepository.get_readiness_score() executed for ent_01 in 42ms',
  },
  {
    id: 'log_1003',
    timestamp: '2025-03-25T14:28:44.102Z',
    level: 'WARNING',
    service: 'worker',
    message: 'ApifyConnectorStub: Rate limit header detected at 85% capacity',
  },
  {
    id: 'log_1004',
    timestamp: '2025-03-25T14:25:00.000Z',
    level: 'ERROR',
    service: 'error',
    message: 'WhatsAppBusinessSDKStub: Exception simulated during refresh_token check',
    details: 'Traceback (most recent call last):\n  File "backend/services/whatsapp.py", line 42',
  },
];

export const MOCK_USERS_LIST: User[] = [
  {
    id: 'usr_01_admin',
    name: 'Carlos Mendoza',
    email: 'admin@asysdigital.com',
    role: 'Administrador',
    department: 'Dirección de Tecnología',
    permissions: ['all:*', 'system:write', 'users:manage', 'audit:execute'],
    status: 'active',
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'usr_02_operator',
    name: 'Valeria Ríos',
    email: 'operador@asysdigital.com',
    role: 'Operador',
    department: 'Estrategia Comercial',
    permissions: ['prospects:read', 'prospects:write', 'campaigns:read'],
    status: 'active',
    createdAt: '2025-02-01T10:30:00Z',
  },
  {
    id: 'usr_03_guest',
    name: 'Invitado Auditor',
    email: 'guest@asysdigital.com',
    role: 'Invitado',
    department: 'Consultoría Externa',
    permissions: ['read:only'],
    status: 'active',
    createdAt: '2025-03-10T14:20:00Z',
  },
];
